name: Continuous Integration

on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23'

      - name: Install just
        run: |
          sudo apt install snapd -y
          sudo snap install just --classic

      - name: Run tests
        run: just test